### ISSUE TITLE
Exception on Chrom , IE browser except Firefox is OK

### ISSUE THREAD

**Issue by chenhao21** [leftstick/generator-es6-angular#16]
Hi,
There is problem on IE and Chrom, where I got below exception on load.
TypeError {stack: "TypeError: undefined is not a function↵    at http…ttp://192.168.92.128:8080/index.bundle.js:3569:15", message: "undefined is not a function"}message: "undefined is not a function"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }__proto__: Error bootstrap e785e48d962e35db60a5:780__webpack_require__.oe
Chrom version:  37.0.2062.0
IE version: 11.09

**Comment by leftstick** [comment]
The error message you provided is pointless, i am sorry for that.

It only says, you are trying to call a function which not defined yet, nothing else. 

The only thing i can tell is, my scaffold should not have compatible issue with browser version you mentioned.

The weird part as you said, Firefox works just fine, i have no idea what kind of stuff is supported in Firefox but not in Chrome & IE 11.

You may want to check in this direction

**Comment by chenaniu** [comment]
This is about IE8 compatibility.
IE8 has js error.

**Comment by chenhao21** [comment]
This is about IE8 compatibility.
IE8 has js error.
网页错误详细信息

用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; InfoPath.2)
时间戳: Sat, 18 Mar 2017 12:50:09 UTC
消息: 缺少标识符
行: 3564
字符: 37
代码: 0
URI: http://192.168.0.8:8080/index.bundle.js

**Comment by leftstick** [comment]
Thanks for reporting this issue, since i've done some testing, i found my scaffold is lacking of `Array.prototype.includes`  and `Promise` support for old browsers, for example: IE 11, and maybe old version of chrome.

They were fixed in latest version `5.0.4`.

But for IE8, if you check [documentation-angular](https://docs.angularjs.org/guide/ie), you would see `IE 8` was not supported for a long time since `angular 1.3` was announced
