### ISSUE TITLE
How to include folders in the builds

### ISSUE THREAD

**Issue by chenhao21** [leftstick/generator-es6-angular#17]
I want to include img folder as well as css js sub folder in deployment.
How can I let webpack export such things to build directory?
In case I need to use <script> tag to include css or js files, I want to refer to my local files not CDN server side files, so I want to include css js folders in my deployment.

Thank you  very much!

**Comment by leftstick** [comment]
For image bundle issue, you should check [file-loader](https://webpack.js.org/loaders/file-loader/) or [url-loader](https://webpack.js.org/loaders/url-loader/). I have `file-loader` configured in `webpack.config.js`, `webpack.config.prod.js`. You can import image in your code, like [logo.co](https://github.com/leftstick/generator-es6-angular/blob/master/generators/app/templates/js/features/home/components/subs/logo/index.co#L9-L20)

`css` works in the same way, check [logo.co](https://github.com/leftstick/generator-es6-angular/blob/master/generators/app/templates/js/features/home/components/subs/logo/index.co#L8)

`webpack` won't help you copy/paste `img`, `css` folder into `build` directory, because the assets are already handled into `build` directory. If you prefer keeping original folder structure, you should read [file-loader](https://webpack.js.org/loaders/file-loader/#filename-templates) with proper update
