### ISSUE TITLE
Controller As Support

### ISSUE THREAD

**Issue by yairneumann11** [leftstick/generator-es6-angular#2]
Is there a reason why you chose not to use the "controller as" syntax?

**Comment by leftstick** [comment]
The generator is a skeleton, which demonstrate how modules can be organized to build an application.

I think It's more easy to read by injecting `$scope` explicitly here in controller, than having a `controller as` in each `Routes.js`.

But never mind, it's fine you do what ever you like in your application, since `controller as` is more POJO for some developers.

**Comment by leftstick** [comment]
It's easy to use `controller as` syntax in the application created by this generator. 

### Add `controllerAs` option in `Routes.js` as following

``` javascript
export default [
    {
        id: 'about',
        isDefault: false,
        when: '/about',
        controller: 'AboutController',
        controllerAs: 'about',
        template: tpl
    }
];
```

### modify your controller

``` javascript
var AboutController = function() {

    this.showSpinner = true;

};

export default [ AboutController ];
```

### update partials

``` html
<div class="container" role="main">
    <span>{{ about.showSpinner }}</span>
</div>
```
