### ISSUE TITLE
using bootstrap's tooltip plugin?

### ISSUE THREAD

**Issue by adamborowski** [leftstick/generator-es6-angular#8]
Is it possible in easy way to use tooltip plugin? By default this statement results undefined:
$(selector).tooltip

I think it is bundled with bootstrap.
I use previous version (just before 3.0)

**Comment by leftstick** [comment]
I imported [angular-strap](http://mgcrea.github.io/angular-strap/#) by default before `3.0.0`, which is an awesome `angular` wrapper of `bootstrap`.

If you'd like to use `tooltip`, check her document here: [tooltip](http://mgcrea.github.io/angular-strap/#/tooltips).

Actually, since i imported `angular-strap`, `tooltip` directive is already there for use:

``` javascript
<a href data-animation="am-flip-x" bs-tooltip data-title="Hello, i'm here">click me</a>
```
